# Generated by Django 5.2.7 on 2026-01-09 13:46

import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
        ('orders', '0002_order_payment_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(default=orders.models.get_payment_expiry),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT', 'Credit/Debit Card'), ('UPI', 'UPI Payment'), ('CASH', 'Cash Payment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddConstraint(
            model_name='exitotp',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_exit_otp_per_order'),
        ),
    ]
