# Generated by Django 5.2.7 on 2026-01-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentattempt_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentAttempt',
        ),
    ]
