# Generated by Django 5.2.7 on 2026-02-12 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_unique_together_and_more'),
        ('malls', '0002_mall_malls_mall_is_acti_ca772f_idx'),
        ('products', '0002_product_gst_rate_product_hsn_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active_cart_per_user_mall',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_user_id_2fa5fb_idx',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='unique_active_cart_per_user'),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='mall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malls.mall'),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='savedcartitem',
            name='saved_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.savedcart'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['user'], name='cart_savedc_user_id_61a3a5_idx'),
        ),
    ]
