# Generated by Django 5.2.7 on 2026-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mall',
            index=models.Index(fields=['is_active'], name='malls_mall_is_acti_ca772f_idx'),
        ),
    ]
