# Generated by Django 5.2.7 on 2026-01-18 16:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_paymentattempt'),
        ('payments', '0002_alter_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='paid_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('CASH', 'Cash'), ('RAZORPAY', 'Razorpay'), ('PHONEPE', 'PhonePe')], default='MOCK', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='attempt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='final_payment', to='payments.paymentattempt'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider'], name='payments_pa_provide_502c98_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_d0489d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_681c90_idx'),
        ),
    ]
